[package]
name = "i-am-rusty"
version = "0.1.0"
authors = ["theskillwithin <austinppeterson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
